apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-bucket
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  storageClassName: gcs-bucket-standard
  volumeName: impactlab-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
