apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: impactlab-data-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Pi
  volumeName: jhub-impactlab-data-pv
  storageClassName: cil-us-west1-analystdata
