apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-bucket
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    gcs.csi.ofek.dev/dir-mode: "0777"
    gcs.csi.ofek.dev/file-mode: "0666"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: scratch-bucket
