apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cilresearch-secretstore
    kind: SecretStore
  target:
    name: argo-workflows-sso
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client-id
      remoteRef:
        key: argo_workflows_sso_client_id
    - secretKey: client-secret
      remoteRef:
        key: argo_workflows_sso_client_secret
