apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-externalsecret # name of the k8s external secret and the k8s secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cilresearch-secretstore
    kind: SecretStore
  target:
    name: sso-client
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: dex.github.clientId
      remoteRef:
        key: argocd_github_client_id
    - secretKey: dex.github.clientSecret
      remoteRef:
        key: argocd_github_client_secret
