- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SSO_DELEGATE_RBAC_TO_NAMESPACE
    value: "true"
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --auth-mode=sso
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --auth-mode=client
- op: replace
  path: /spec/replicas
  value: 2
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    { "requests": { "cpu": "0.1", "memory": "500Mi"}, "limits": { "cpu": "1", "memory": "1Gi"} }
