apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow
subjects:
  - kind: ServiceAccount
    name: workflow
roleRef:
  kind: Role
  name: workflow
  apiGroup: rbac.authorization.k8s.io
