# Argo Workflows mounts the Workflow ServiceAccount token secret.
apiVersion: v1
kind: Secret
metadata:
  name: workflow.service-account-token
  annotations:
    kubernetes.io/service-account.name: workflow
type: kubernetes.io/service-account-token
