apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.11.0
    helm:
      values: |
        serviceAccount:
          name: "external-secrets"
          annotations:
             iam.gke.io/gcp-service-account: external-secrets@cilresearch.iam.gserviceaccount.com
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
