apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - resources/argo-workflows-sso-externalsecret.yaml
  - resources/argocd-server-ingress.yaml
  - resources/cilresearch-secretstore.yaml
  - resources/letsencrypt-prod-issuer.yaml
  - resources/sso-client-externalsecret.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.6/manifests/ha/install.yaml

patchesStrategicMerge:
  - patches/argocd-dex-server-deployment.yaml
  - patches/argocd-cm.yaml
  - patches/argocd-rbac-cm.yaml
