apiVersion: v1
kind: PersistentVolume
metadata:
  name: impactlab-data-scratch
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Pi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scratch-bucket
  csi:
    driver: gcs.csi.ofek.dev
    volumeHandle: impactlab-data-scratch
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: jhub
