apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-secret
spec:
  secretName: argo-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "workflows.cilresearch.org"